AsutpWeb/Models/OracleCon.cs
using System;
using System.Collections.Generic;
using System.Data.OracleClient;

namespace AsutpWeb.Models
{
    public class OracleCon
    {
#pragma warning disable CS0618 // Тип или член устарел
        private readonly OracleConnection _connection = new OracleConnection("Data Source = 192.168.137.70/zxp; " +
                                        "User id = useridb; Password = zxp1234");
#pragma warning restore CS0618 // Тип или член устарел
        public OracleCon()
        {
            try
            {
                _connection.Open();
            }
            catch (Exception)
            {
                // ignored
            }
        }

        public List<object> OracleQury(string qury, int lenght)
        {
            var dt = new List<object>();

#pragma warning disable 618
            var cmd = new OracleCommand
            {
                Connection = _connection,
                CommandText = qury
            };
#pragma warning restore 618

            var dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                var models = new SheetGageModels.SheetGage
                {
                    DateStart = dr.GetDateTime(0),
                   // Shift = dr.GetInt32(1)
                };
                //var test = (dr.GetValue(a));
                //dt = (dr.GetDateTime(a));


                dt.Add(models); 

               
            }

            dr.Close();

            return dt;
        }

        public void OracleCloseCon()
        {
            _connection.Close();
        }
    }
}

/*





            var cmd = new OracleCommand
            {
                Connection = connection,
                CommandText = qury //"Select max(datetime) from test"
            };

#pragma warning restore 618
                
            var dr = cmd.ExecuteReader();

            dr.Read();

            //var dt = Convert.ToDateTime(dr.GetDateTime(0));

           dr.Close();


        }
          catch
              (Exception)
          {
              // ignored
          }
          //return IAsyncResult;
      }
       public List<int> TestList() { return new List<int>(0); }
    }
}
*/

AsutpWeb/Models/SheetGageModels/SheetGage.cs
using System;

namespace AsutpWeb.Models.SheetGageModels
{
    public class SheetGage
    {
        public DateTime DateStart { get; set; }

        public DateTime DateEnd { get; set; }

        public int Shift { get; set; }

    }
}

AsutpWeb/Controllers/HomeController.cs
using System.Web.Mvc;
using AsutpWeb.Models;

namespace AsutpWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
          return View();
        }

    }
}

AsutpWeb/Controllers/SheetGageController.cs
using System;
using System.Data.OracleClient;
using System.Web.Mvc;
using AsutpWeb.Models;

namespace AsutpWeb.Controllers
{
    public class SheetGageController : Controller
    {
        // GET: SteelGage
        public ActionResult SheetGage()
        {
            var ora = new OracleCon();
            
            ViewBag.Test = ora.OracleQury("Select datetime from test where datetime IS NOT null", 1);

            ora.OracleCloseCon();
            
            //oracleCon:OracleDataReader=Convert.ToDateTime() //var dt = Convert.ToDateTime(dr.GetDateTime(0));

            return View();
        }
    }
}

AsutpWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div>
    <h3>Перевалки</h3>
    <table class="table table-hover">
        <tr>
            <td><p>№ Клети</p></td>
            <td><p>№ Нижнего валка</p></td>
            <td><p>№ Верхнего валка</p></td>
            <td><p>Диаметр нижнего валка</p></td>
            <td><p>Диаметр вехнего валка</p></td>
            <td><p>Редактировать</p></td>
        </tr>
       
</table>
</div>

AsutpWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Сектор АС</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Участок №9 сектор АС", "SheetGage", "SheetGage", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домой", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - УА уч.№9 сектор АС</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AsutpWeb/Views/SheetGage/SheetGage.cshtml
@{
    ViewBag.Title = "УА";
}

<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>DateStart</th>
                <th>Lastname</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
        @foreach (var b in ViewBag.Test)
        {
            <tr>
                <td>@b.DateStart</td>
                <td>testi</td>
                <td>test@example.com</td>      
            </tr>
        }
        </tbody>
    </table>
</div>